name: Semantic Release

on:
  push:
    branches:
      - main

concurrency:
  group: {% raw %}${{ github.workflow }}-${{ github.ref_name }}{% endraw %}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  test:
    uses: ./.github/workflows/test.yml

  release:
    needs: [lint, test]
    runs-on: ubuntu-latest
    outputs:
      released: {% raw %}${{ steps.release.outputs.released }}{% endraw %}
      tag: {% raw %}${{ steps.release.outputs.tag }}{% endraw %}

    permissions:
      contents: write

    steps:
      - name: Generate bot app token
        id: generate_token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf
        with:
          app-id: {% raw %}${{ secrets.MY_RELEASER_ID }}{% endraw %}
          private-key: {% raw %}${{ secrets.MY_RELEASER_PRIVATE_KEY }}{% endraw %}

      - name: Checkout
        uses: actions/checkout@v6
        with:
          token: {% raw %}${{ steps.generate_token.outputs.token }}{% endraw %}
          fetch-depth: 0

      - name: Install Poetry
        run: pip install poetry==2.0.1

      - name: Set up Python {{ cookiecutter.python_version }}
        uses: actions/setup-python@v6
        with:
          python-version: "{{ cookiecutter.python_version }}"
          cache: 'poetry'

      - name: Install dependencies
        run: poetry install

      - name: Semantic Version Release
        id: release
        uses: python-semantic-release/python-semantic-release@350c48fcb3ffcdfd2e0a235206bc2ecea6b69df0
        with:
          github_token: {% raw %}${{ steps.generate_token.outputs.token }}{% endraw %}
          git_committer_name: "semantic-release"
          git_committer_email: "semantic-release@users.noreply.github.com"
          build: false

      - name: Build package
        if: steps.release.outputs.released == 'true'
        run: poetry build

      - name: Upload to GitHub Release Assets
        uses: python-semantic-release/publish-action@310a9983a0ae878b29f3aac778d7c77c1db27378
        if: steps.release.outputs.released == 'true'
        with:
          github_token: {% raw %}${{ steps.generate_token.outputs.token }}{% endraw %}
          tag: {% raw %}${{ steps.release.outputs.tag }}{% endraw %}

      - name: Upload Distribution Artifacts
        uses: actions/upload-artifact@v6
        if: steps.release.outputs.released == 'true'
        with:
          name: distribution-artifacts
          path: dist
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: release
    if: {% raw %}${{ needs.release.outputs.released == 'true' }}{% endraw %}

    environment:
      name: pypi
      url: https://pypi.org/p/{{ cookiecutter.package_name }}

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v7
        with:
          name: distribution-artifacts
          path: dist

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e
        with:
          packages-dir: dist
